fs: sdcardfs: Use bitwise instead of logical operator
error: use of logical '||' with constant operand
error: | has lower precedence than !=; != will be evaluated first